<?php 
/**
 * Make_Sample extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Make
 * @package        Make_Sample
 * @copyright      Copyright (c) 2018
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Mysample list template
 *
 * @category    Make
 * @package     Make_Sample
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_mysamples = $this->getMysamples(); ?>
<div class="page-title mysample-title">
    <h1><?php echo Mage::helper('make_sample')->__('Mysamples') ?></h1>
</div>
<?php if ($_mysamples->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="mysample-list-container">
    <?php foreach ($_mysamples as $_mysample) : ?>
        <div class="mysample-list-item">
            <a href="<?php echo $_mysample->getMysampleUrl()?>">
                <?php echo $_mysample->getTitle();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('make_sample')->__('There are no mysamples at this moment');?>
<?php endif;?>
